### ISSUE TITLE
Merge jjohannes/missing-metadata-guava into this plugin

### ISSUE THREAD

**Issue by vlsi** [jjohannes/java-ecosystem-capabilities#2]
Looks like https://github.com/jjohannes/missing-metadata-guava is related, and the name of `java-ecosystem-capabilities` sounds good for an umbrella project.

**Comment by jjohannes** [comment]
Thanks for the feedback! Will give this give this some thoughts (also related to #1).

**Comment by jjohannes** [comment]
I think I would like to do this for a potential `.1.0`.

**Comment by jjohannes** [comment]
_missing-metadata-guava_ covers two aspects compared to the other rules in this plugin:

1. Capabilities around Guava (fit in here well)
2. Add additional variant information (android vs standard-jvm)

The first fits perfectly in here. The second is a bit different compared to other rules and is strictly not directly about Capabilities only. But it is very related so I think it fits in here as well.
